### ISSUE TITLE
краш при выборе меню в настройках (отсюда невозможность смены темы)

### ISSUE THREAD

**Issue by ghost** [gnoemes/Shikimori-App-Remastered#3]
```
androidx.fragment.app.d$b: Unable to instantiate fragment com.gnoemes.shikimori.presentation.view.settings.fragments.Settings(.+)Fragment: make sure class name exists
 at androidx.fragment.app.h.b(Unknown Source:59)
 at androidx.fragment.app.h.a(Unknown Source:0)
 at com.gnoemes.shikimori.presentation.view.settings.SettingsActivity.a(Unknown Source:34)
 at androidx.preference.g.a(Unknown Source:43)
 at androidx.preference.Preference.I(Unknown Source:35)
 at androidx.preference.Preference.a(Unknown Source:0)
 at androidx.preference.Preference$1.onClick(Unknown Source:2)
 at android.view.View.performClick(View.java:6312)
 at android.view.View$PerformClick.run(View.java:24811)
 at android.os.Handler.handleCallback(Handler.java:794)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:6651)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.gnoemes.shikimori.presentation.view.settings.fragments.SettingsAboutFragment" on path: DexPathList[[zip file "/data/app/com.gnoemes.shikimori-BFCA6p72jTP133kMyhX_XQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.gnoemes.shikimori-BFCA6p72jTP133kMyhX_XQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 at androidx.fragment.app.h.c(Unknown Source:10)
 at androidx.fragment.app.h.b(Unknown Source:0)
 ... 15 more
```
При сборке релизной версии. Видимо, надо в proguard добавить эти классы.
**UPD:** `-keep public class * extends androidx.preference.PreferenceFragmentCompat` в прогуард фиксит.

**Comment by gnoemes** [comment]
Не заметил и написал костыль. Поправил в #7
